### ISSUE TITLE
Terminal cursor background and text

### ISSUE THREAD

**Issue by duhok1** [Monokai/monokai-pro-vscode#127]
Currently, the theme uses same color for terminal cursor text and background, thus when using a "block" style cursor ... it blocks the character (letter) which the cursor is at.

![Peek 2019-04-03 16-57](https://user-images.githubusercontent.com/46654846/55512709-c4ffde80-5631-11e9-90ab-a10dcab10559.gif)

Please consider using different colors for background and text of the cursor.

**Comment by Monokai** [comment]
Fixed in 1.1.13

**Comment by wang95** [comment]
still have the same issue in 1.1.13

VS Code Ver: 1.36.1 
OS: Windows 10.0.17134 x64
![cursor_issue](https://user-images.githubusercontent.com/5316838/62070365-ecc42380-b26c-11e9-916a-27c7aa47ed0f.png)
