### ISSUE TITLE
C++ function parameters in VS Code

### ISSUE THREAD

**Issue by aheidelberg** [Monokai/monokai-pro-vscode#38]
Function parameters in C++ are highlighted as functions (green instead of white)

VS Code
![screen shot 2017-12-03 at 12 17 48](https://user-images.githubusercontent.com/22153826/33524855-7d2e64a0-d824-11e7-8d0b-fec64b0a41c8.png)

Sublime
![screen shot 2017-12-03 at 12 19 41](https://user-images.githubusercontent.com/22153826/33524856-7d4c5884-d824-11e7-831a-6426b55bac9e.png)

**Comment by Monokai** [comment]
Fixed in 1.1.5

**Comment by aheidelberg** [comment]
Unfortunately this is not fixed for me in 1.1.5.
<img width="897" alt="screen shot 2018-01-17 at 12 15 15" src="https://user-images.githubusercontent.com/22153826/35040114-45a966a4-fb80-11e7-8ac3-0ac165da0c1a.png">

**Comment by Monokai** [comment]
VSCode fixed their syntax definitions

**Comment by aheidelberg** [comment]
I don't know what I'm doing wrong. It still looks like in my screenshots from above.
I tried VS Code on Mac and Windows, normal and insider build, with and without C++ extension. Monokai Pro version 1.1.6
